### ISSUE TITLE
data-injestion is very flow in output table

### ISSUE THREAD

**Issue by sara85sara** [Azure/azure-kusto-python#233]
I am using following code in databricks to insert the data into kusto table, but its very slow in output that I am not able to see the data in kusto table, even after multiple refresh.. its coming very slowly..

from azure.kusto.data.request import KustoClient, KustoConnectionStringBuilder
from azure.kusto.data.helpers import dataframe_from_result_table
from azure.kusto.ingest import KustoIngestClient,IngestionProperties

# Establish connection to Kusto using Service Principal.
cluster = "https://ingest-***.kusto.windows.net"
client_id = "***"
client_secret = "*****"
authority_id = "72f988bf-86f1-41af-91ab-2d7cd011db47"

kcsb = KustoConnectionStringBuilder.with_aad_application_key_authentication(cluster, client_id, client_secret, authority_id)
client = KustoIngestClient(kcsb) 

ingestion_props = IngestionProperties(
    database="****",
    table="Employee"   
)

# ingest from dataframe
import pandas

fields = ["id", "name", "value"]
rows = [[1, "abc", 153], [2, "cde", 999]]

df = pandas.DataFrame(data=rows, columns=fields)
client.ingest_from_dataframe(df, ingestion_properties=ingestion_props)

**Comment by danield137** [comment]
Hi @sara85sara, 

Ingesting for a dataframe uses (queued ingestion mechanism )[https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/data-ingestion/].

As such, since it is built for high throughput usage, it aggregated data downstream prior to ingestion which can result in latency.

One option to speed it up for testing purposes is using the flush immediately flag

```python
IngestionProperties(
...
flush_immediately=True
)
```

In general I would advise to ask this over StackOverflow as this is more of a general question than a bug.
