### ISSUE TITLE
Efficient data access and result from Python

### ISSUE THREAD

**Issue by cdeil** [Azure/azure-kusto-python#372]
In our code we use ` azure.kusto.data.helpers.dataframe_from_result_table` and it results in memory bloat:

```
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 315 entries, 0 to 314
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype              
---  ------     --------------  -----              
 0   sensor     315 non-null    object             
 1   timestamp  315 non-null    datetime64[ns, UTC]
 2   value      315 non-null    Float64            
dtypes: Float64(1), datetime64[ns, UTC](1), object(1)
memory usage: 7.8+ KB
```

We only need `float32` precision. Can you offer a flag that would allow us to avoid going via `Float64` which you hardcode?

Another huge memory savings would be to use categorical instead of strings:
https://pandas.pydata.org/pandas-docs/stable/user_guide/categorical.html#categorical-data

Can you support more efficient memory representation, either as convenience function, but ideally starting from scratch internally with the query and network traffic with pandas or Arrow?

https://github.com/Azure/azure-kusto-python/blob/1a8a90e859938abd31cc2629b6f6de6b6f0ae099/azure-kusto-data/azure/kusto/data/helpers.py#L33-L65

**Comment by yihezkel** [comment]
Hi @cdeil,

Thanks for bringing this up!

We do want to minimize memory **waste**, and looking at the code we see we should break up:
`elif col.column_type == "int" or col.column_type == "long": 
    frame[col.column_name] = frame[col.column_name].astype("Int64")`
To include:
`elif col.column_type == "int":
    frame[col.column_name] = frame[col.column_name].astype("Int32")`

But regarding `float`s, we don't want to reduce precision by default. And in terms of adding a flag, it's unclear that this would be a popular feature (see option (1) below).

We therefore suggest 2 options:
1) Confirm that the memory savings are worth the effort. In your test, I see 315 rows using only (an extra?) 7.8 KB. I might suggest a test using a much larger set of your data, comparing the memory usage using `Float32` vs `Float64` (by changing the method, as suggested in (2) below).
2) If your answer to (1) is in the affirmative or as part of testing (1) above, you can change `dataframe_from_result_table` in your implementation to use `Float32`.

In terms of `Categorical`, I'm not as familiar with it, but based on the documentation it's "for representing data that can take only a limited, fixed set of values." Based on that, I don't think we'd want to use it by default, and the question again becomes how useful it is to the broader population of the SDK's users, to inform whether to add a flag or to expect the rare users who require it to customize this method as they need it.

**Comment by cdeil** [comment]
@yihezkel - I think basically my feature request here goes much beyond what was implemented in #376.

I'm thinking ADX is a big data analytics database, so it should offer efficient clients to ingest and query big data like e.g. a GigaByte. Specifically for us, our data science flows are running in K8S pods in Python & pandas and we have to watch the memory usage for machine learning training. Currently it's very inefficient because (a) your Python client uses JSON on the wire and (b) non-efficient memory layout for `pandas.DataFrame`.

Specifically we have (and I think it's very common?) sensor tags as strings that are repeated million-fold for time series. For that pandas introduced this:
https://pandas.pydata.org/pandas-docs/stable/user_guide/categorical.html
For now we can call
https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.astype.html
to go to the efficient memory layout after the data fetch.

That works for us for now, but generally the big feature request I'm putting here is to change the client or even ADX itself to support efficient ADX -> memory for more efficient use of bandwidth and RAM during the fetch and de-serialisation.
See https://arrow.apache.org/docs/python/pandas.html

We don't absolutely need this for our current use cases, we can increase node RAM or fetch in chunks manually or something, but I think just generally the big data ecosystem (e.g. InfluxDB, Snowflake) are moving to native Parquet and Arrow support, so I wanted to ask if it's planned or give +1 to consider introducing it for ADX also.

cc @cosh, @ratanasov working on ADX POC for HeidelbergCement.

**Comment by yihezkel** [comment]
Thanks for the suggestion, @cdeil !
It's helpful to understand how prevalent these needs are.

I want to be clear about the scope of your request -
1) You'd like the ability to use `Categorical`.
If it's sufficiently common among the SDK's users and potential users to have columns with repetitive strings, I agree that it may be worthwhile offering a way to indicate that a column has such data. But I assume there's a penalty to using `Categorical` over string if the data has high cardinality, otherwise the docs I referenced in my previous comment wouldn't have restricted the suggestion of when to use it. I can research this further when I have time, but I'd appreciate if you have any insight into this.

2) Per your initial comment, you'd like to reduce the memory footprint for `int32` (already done) and `float32`.
But the question I asked above remains regarding how much of a memory impact `float32` would have on your use cases in practice.

3) Support for querying to Parquet/Arrow format(s) directly, via recommended approaches in the link you posted for maximum efficiency.

Am I missing any requests?

**Comment by cdeil** [comment]
For IoT use cases, I think string columns commonly are categorical and represent device or sensor IDs and repeat a lot and category dtype is better.For logs or text-bases use cases I think a normal string is needed. So since ADX doesn't have a native categorical type in the DB, `str` is the right default (can represent any data) and categorical is the significant optimisation for IoT.

The savings for float32 vs float64 is 50% for the value column. But typically there's also a timestamp and sensor ID columns that are typically 4 or 8 byte and then the overall savings by that value dtype change isn't so large, maybe 20%. I see now ADX doesn't support float32 natively: https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/scalar-data-types/unsupported-data-types

So yes, both category and float32 dtype would have to be opt-in and user-specified to use for a given column, and the request mostly makes sense in combination with the third one to read to Arrow memory directly instead of like now ADX -> JSON -> list/dict/str/float/int -> pandas, since as long as the inefficient representation remains on read one can just chain `data_frame.astype(...)` to change dtypes after already.

@yihezkel - try starting with a 1 GB Parquet file of IoT data (timestamp, sensorName, value) and write it to ADX. Then try pulling it out again with the Python client into a dataframe with good representation (categorical for sensorName, matching what Parquet does on disk to dict-encode) and see how much memory you need and how much goes over the wire. This is my request here: please make this more efficient for IoT use cases with Python.

**Comment by yihezkel** [comment]
Thanks @cdeil ! These suggestions are very helpful.

As you noticed, ADX doesn't support `Float32` columns. So we couldn't automatically convert any columns from the result table into Panda `Float32`s. And as you pointed out, we couldn't automatically convert to Panda `Categorical`s either.

We have to balance adding features that are useful to even just some users with keeping the interface reasonably simplified for most use cases. Therefore, until we see that there's sufficient demand, we're not sure it's a good idea to change `azure.kusto.data.helpers.dataframe_from_result_table` to accept a flag or column definitions to specify the target type (including `Float32` and `Categorical`). We're still considering it, but in the meantime, there's a simple solution - consider cloning the repo and editing this method directly, or of course chaining `data_frame.astype(...)` afterwards, as you mentioned.

In terms of the bigger-impact request, I also don't foresee adding to the ADX service the ability to return results in Arrow/Parquet format. In any case, it seems to me gzipped `json` is efficient over the wire. So the primary opportunity for savings comes from our conversion of the `json` we receive to a `KustoResponseDataSet`/`KustoResultTable`.
Do you agree with this analysis?
If so, I think the best approach would be add to the Python SDK a query method that returns the `json` it received from the wire, which can then be converted to `Parquet`/`Arrow`, skipping the intermediate `KustoResponseDataSet`/`KustoResultTable`. See for example `client.KustoClient._execute` where we can return just the `response_json` instead of the last line. The `json` can then be converted to `Parquet`/`Arrow`, including flags/parameters to indicate column types (like `Float32` and `Categorical`).

@adieldar read this thread, and had a suggestion:
"My recommendation would be to train & score using the python() plugin (https://docs.microsoft.com/azure/data-explorer/kusto/query/pythonplugin) on our Python sandboxes. Then you don't have to export the data at all as the Python is run on the existing compute nodes where the data resides. But training cannot always be done on our sandbox, mainly if it requires long batch processing and/or GPU support."

**Comment by cdeil** [comment]
@yihezkel  - thanks for the information and advice!

At the moment we use `dataframe_from_result_table` followed by `astype` (see code example below).

I don't have a benchmark, but it's not fast. Pulling out a few GB from ADX takes over an hour. I don't know where the bottleneck is. My network and computer are fast, so I presume it could be ADX having to load the data and JSON encode it, and that the issue isn't with JSON deserialisation and Python objects begin slow to create before they safely land in the efficient dataframe. But I don't know or have time to investigate, it works good enough for us for now.

What our data engineer implemented is a local DuckDB cache for historic data and data scientists to avoid querying ADX often, that helps a lot.

Maybe the ADX team and MS can consider to make the big invest into more efficient solutions to follow the lead of e.g. Snowflake or others that now offer efficient Arrow solutions! :-)

I see at https://pandas.pydata.org/docs/dev/whatsnew/v2.0.0.html Pandas is also continuing to grow it's support for Arrow.

---

Helper function with some options to avoid timeouts:

```python
def query(kql: str, streaming=False) -> pd.DataFrame:
    """Execute a KQL query."""
    client, db = get_client()

    properties = ClientRequestProperties()
    properties.set_option("notruncation", True)
    properties.set_option("norequesttimeout", True)

    if streaming:
        response = client.execute_streaming_query(db, kql, properties=properties)
        result = next(response.iter_primary_results())
    else:
        response = client.execute(db, kql, properties=properties)
        result = response.primary_results[0]

    return dataframe_from_result_table(result)
```

Caller example:

```python
df = query(kql, streaming=True)
df["value"] = df["value"].astype("float32")
```
